### PR TITLE
Upgrade to .NET7, build/usability fixes, generate NuGet

### PR DESCRIPTION
**Pull request by meruune**
- Upgraded to .NET 7 (Core)
- Generate NuGet on build
- Proper proj/file references

Also added a null check on controller data (test project)
NuGet build action already copies/packs all the needed files,
I've updated it with some basic data needed to publish.
Please test and consider adding to NuGet/GH Packages, thanks!

### CODE REVIEW

**Comment by Timocop** [comment]
I never actually used .NET Core before, but I probably should. 
Sadly, I mainly use WinForms using .NET Framework (because I'm used to it) and .NET Core libraries do not work with .NET Framework apps.
If its somehow possible to generate .NET Core and .NET Framework DLLs in the same project for releases that would be great. Otherwise, I have to make a branch for .NET Core.

(Also, no need to change ``Module1.vb`` it's just for testing, not an actual sample.)

**Comment by meruune** [comment]
Oh, sorry

Sure, should be possible by targeting `netstandard2.0` in the API and netfx > 4.6 in the WPF app, I'll try to update the files for that a bit later.

BTW you can try autoupgrading to .NET Core with [this](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/intro), [WPF-specific version](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-winforms-framework) if you don't have any hard netfx deps (not present in the compatibility package)

**Comment by Timocop** [comment]
Indeed, .NET Standard 2.0 seems to be a good balance between .NET Framework and .NET Core.

**Comment by meruune** [comment]
Should be ok now, also tested it with a netfx console app to be sure.
Note, it's not gonna load unless you `<Prefer32Bit>false</Prefer32Bit>`

**Comment by Timocop** [comment]
Since the C++ CAPI is 64-Bit, its best to make this 64-Bit only as well. Looks good, thank you!
I will obviously still change a lot of stuff, this repo is still very WIP.

**Pull request merged**
